inherit_gem:
  bixby: bixby_default.yml

inherit_from: .rubocop_todo.yml

# By default RSpec/MessageSpies has the following:
#   Prefer have_received for setting message expectations. Setup form as a spy using allow or instance_spy.
# The default assumes EnforcedStyle is 'have_received'. Most of our specs are 'receive'
RSpec/MessageSpies:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['included']
  Exclude:
    - 'qa.gemspec'
    - 'spec/**/*.rb'

AllCops:
  TargetRubyVersion: 2.1
  DisplayCopNames: true
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
  Include:
    - '**/Rakefile'

#Metrics/LineLength:
#  Enabled: false
#
#Metrics/AbcSize:
#  Enabled: false
#
#Metrics/MethodLength:
#  Enabled: false
#
#Style/BlockDelimiters:
#  Exclude:
#    - 'spec/**/*'
#
#Style/BlockEndNewline:
#  Exclude:
#    - 'spec/**/*'
#
#Style/MultilineBlockLayout:
#  Exclude:
#    - 'spec/**/*'
#
#Style/IndentationConsistency:
#  EnforcedStyle: rails
#
#Style/CollectionMethods:
#  PreferredMethods:
#    collect: 'map'
#    collect!: 'map!'
#    inject: 'reduce'
#    detect: 'find'
#    find_all: 'select'
#
#Style/WordArray:
#  Enabled: false
#
#Style/RegexpLiteral:
#  Enabled: false
#
#Style/StringLiterals:
#  Enabled: false
#
#Style/ClassAndModuleChildren:
#  Enabled: false
#
#Style/Documentation:
#  Enabled: false
#
#Style/HashSyntax:
#  Exclude:
#
#Style/LineEndConcatenation:
#  Exclude:
#
#Style/PredicateName:
#  Exclude:
#
#Style/GlobalVars:
#  Exclude:
#    - 'spec/**/*'
#
#Style/SingleLineBlockParams:
#  Enabled: false
#
#Style/ClassVars:
#  Exclude:
#
#Style/SignalException:
#  Enabled: false
#
#Style/FileName:
#  Exclude:
#
#Style/VariableName:
#  Exclude:
#    - 'lib/share_notify/push_document.rb'
#
#Style/FrozenStringLiteralComment:
#  Enabled: false
#
#RSpec/ExampleWording:
#  CustomTransform:
#    be: is
#    have: has
#    not: does not
#    NOT: does NOT
#  IgnoredWords:
#    - only
#
#RSpec/ExpectActual:
#  Enabled: false
#
#RSpec/FilePath:
#  Enabled: false
#
#RSpec/InstanceVariable:
#  Enabled: false
#
#RSpec/DescribeClass:
#  Exclude:
#    - 'spec/lib/tasks/mesh.rake_spec.rb'
#
#RSpec/LetSetup:
#  Enabled: false
#
#RSpec/MessageExpectation:
#  Enabled: false
#
#RSpec/MultipleExpectations:
#  Enabled: false
#
#RSpec/NestedGroups:
#  Enabled: false
#
#RSpec/LeadingSubject:
#  Enabled: false
