language: ruby
rvm:
  - 2.0
  - 2.1

gemfile:
  - gemfiles/gemfile.rails4
  - gemfiles/gemfile.rails4.1

notifications:
  irc: "irc.freenode.org#projecthydra"

before_install:
  - gem install bundler

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
