language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.1

notifications:
  irc: "irc.freenode.org#projecthydra"

before_install:
  - gem install bundler

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
 