language: ruby
sudo: false
rvm:
  - 2.4.1
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - "RAILS_VERSION=5.0.6"
    - "RAILS_VERSION=5.1.4"

before_install:
  - gem update --system
