language: ruby
cache: bundler
sudo: false
rvm:
  - 2.2
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

  matrix:
    - "RAILS_VERSION=4.1.8"
    - "RAILS_VERSION=4.2.0"

matrix:
  allow_failures:
    - env: "RAILS_VERSION=4.2.0"

notifications:
  irc:
    channels:
      - "irc.freenode.org#projecthydra"
    template:
      - "%{repository}//%{branch}@%{commit} by %{author}: %{message} - %{build_url}"
