language: ruby
sudo: false
rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - "RAILS_VERSION=5.0.7"
    - "RAILS_VERSION=5.1.6"
    - "RAILS_VERSION=5.2.1"

before_install:
  - gem update --system
